import {
  BitcoinIcon,
  LitecoinIcon,
  EthereumIcon,
  DogecoinIcon,
  TetherIcon,
  CardanoIcon,
  SolanaIcon,
  ChainlinkIcon,
  PolkadotIcon,
  GasIcon,
  TrueUSDIcon,
  UniswapIcon,
} from "../assets/Icons";
export const cryptoIcons: any = {
  BTC: BitcoinIcon,
  LTC: LitecoinIcon,
  ETH: EthereumIcon,
  DOGE: DogecoinIcon,
  USDT: TetherIcon,
  SOL: SolanaIcon,
  ADA: CardanoIcon,
  LINK: ChainlinkIcon,
  DOT: PolkadotIcon,
  GAS: GasIcon,
  UNI: UniswapIcon,
  TUSD: TrueUSDIcon,
};
